### ISSUE TITLE
Format code for Moodle feature

### ISSUE THREAD

**Issue by fuhrmanator** [ethan-ou/vscode-gift#9]
I am back to making a ton of quizzes with code, so I think I understand what @didoudiaz was asking for in #7

For example, I have a GIFT question where I want to show some code:

    [markdown]What type is given to the `x` field in the following class:    
    class A {
      x = 1;
    }
    { =number ~any }

To make the code part work with Moodle in markdown, I have to do the following transformations:
- surround code with fences (a line with three backticks at the start and again at the end of the code)
- escape all special characters in GIFT `=`, `{`, `}`, etc.
- replace newlines with `\n`
- add a non-breaking space as the first space on the line (as discussed in #7) to allow indenting to work (~not entirely sure this will work~)

I don't think I can do this with a snippet, at least it doesn't seem so.

So, to describe what I would like, it would be to select the "code" in VSCode then apply some "Format code for moodle GIFT" command, that would produce:

    ```\nclass A \{\n&nbsp;  x \= 1;\n\}\n```

Do you think it's something you can try?

**Edit** For it to work in markdown format, the `&nbsp;` actually must be a true non-breaking space (a single character). I just tested it in Moodle.

**Comment by fuhrmanator** [comment]
I'm thinking that the command needs a variant for Markdown, HTML and perhaps Moodle formats. It could try to deduce this from the GIFT question itself, but I think it's probably not going to work since the code's not escaped. It's probably easiest to let the user decide which formatting to apply?

**Comment by fuhrmanator** [comment]
To insert the non-breaking space to allow indenting in Moodle, it might be easiest (once linebreaks are converted to literal `\n`) to just do a global replace of the literal `\n ` (regular space) with `\n_` (where _ is the non-breaking space character).

**Comment by fuhrmanator** [comment]
I could give you some test cases (before and after) and I think that would make your coding easier - let me know if you want me to proceed (I can attach them here since the non-breaking spaces won't be easy to see in markdown here).

**Comment by ethan-ou** [comment]
If you have tests or even some mock Javascript code that does the processing you think is necessary, I'm happy to put it into an action. Do you have a list of actions you think should be implemented in your head? So one for markdown, HTML and moodle, and also one to undo these actions?

**Comment by fuhrmanator** [comment]
I'm always using markdown, as it's simpler with GIFT. Maybe it's not worth implementing it for the other formats (yet?).

I have done a jest test that passes for one case at https://github.com/fuhrmanator/gift-codefence

You can see the code at: https://github.com/fuhrmanator/gift-codefence/blob/83c1c76a7f257c1f3b893d2f91149579c954460b/src/formatCodeFence.ts#L1-L9

**Comment by ethan-ou** [comment]
Here's a preliminary build of escaping and unescaping using the code you wrote. You should be able to install it by dragging into your extensions folder. More on that in the [VSCode Docs](https://code.visualstudio.com/api/working-with-extensions/publishing-extension#packaging-extensions).

[vscode-gift-0.1.7.vsix.zip](https://github.com/ethan-ou/vscode-gift/files/6986234/vscode-gift-0.1.7.vsix.zip)

You should be able to cross-reference with the code too: https://github.com/ethan-ou/vscode-gift/blob/4e545693f3286df88cae7f9e20e394a97511982d/client/src/GIFTHelpers.ts#L67-L121

Give it a try and see if you need to make any adjustments.

**Comment by fuhrmanator** [comment]
Very cool - I was able to make it work and even tested a GIFT import to Moodle and it's perfect.

My only feedback at this time is about the lightbulb menu being the mechanism to access the feature. I'm perhaps too old-school, but I would expect to select the text I want to escape, then right-click and see a menu option (kind of like a refactor). The reason I don't like the lightbulb menu is that it proposes the corrective options without much intelligence. I'm not sure what makes it trigger the lightbulb (maybe it's found some syntax errors due to unescaped special characters in the code?) but applying them is not really smart enough to do a proper resolution, as in other lightbulb actions I know (quick fix). That is, it doesn't properly select the text before escaping it (it also can't tell the difference between escaped and unescaped). So, I find it inconsistent in this way. It also took me a few moments to realize you put it there (not obvious, but my old-school baggage maybe is hurting me there).

Would it be possible to make a context (right-click) menu if text is selected? It could also be a CTRL-SHIFT-P command in case someone wants to script it or make a keyboard shortcut (something I will definitely want to do).

Another complementary option, since often I copy the source code from another window, would be to allow pasting escaped code. Again, if this feature was a command, you can make a key binding such as CTRL-SHIFT-V (or something not used by other commands).

In any case, this will be a time saver and is a great example of tech to reduce accidental complexity (especially the non-breaking space to preserve indentation in Moodle hack)! Thanks again as always!

**Comment by ethan-ou** [comment]
For the first point, you should still be able to access those options through the Refactor menu if you right click on a bunch of selected text:

![Code_y3BqqjzF15](https://user-images.githubusercontent.com/45083970/129461973-74a23dc3-9c1b-4412-8315-27b4a5adfb43.png)

If you wanted I could also add these to the CTRL-SHIFT-P menu too. They're already there if you search "Refactor" or use the keyboard shortcut CTRL-SHIFT-R to trigger the Refactor menu.

![Code_IAPOiHDJIC](https://user-images.githubusercontent.com/45083970/129461959-7e6b1f79-9c6c-493d-8d0e-db035f8a1196.png)

**Comment by fuhrmanator** [comment]
> I could also add these to the CTRL-SHIFT-P menu too. They're already there if you search "Refactor" or use the keyboard shortcut CTRL-SHIFT-R to trigger the Refactor menu.

OK - I didn't realize they were under Refactor, which makes sense. 

Here's my use case, so you can understand why a separate command would be useful. I'm making quizzes that have code fences in the question and often also in the answers, so escaping is something I have to do a lot. When it's under the **Refactor...** menu, I don't think I can map the specific action (e.g., "Escape ...") to a key binding. With CTRL-SHIFT-R I can see the list of things, but then I have to click again to pick "Escape Markdown ..." which is extra clicks and navigating a menu. If there's a command I can bind to, I just select the code block, do the key sequence and I'm done.

A couple other comments for you to think about (I'm really being picky here 🤓): 
- after doing the Escape function, the selection doesn't include all of the text that was generated (the initial `\n```\n` is not included in the selection), which is somewhat inconsistent. 
- perhaps a better name for the command is "Escape code (Moodle Markdown)" since it's really a Moodle-specific formatting
- perhaps the unescape function can be intelligent, backing up to find the `\n```\n` and automatically selecting until the final `\n``` ` to apply the unescape function.

**Comment by ethan-ou** [comment]
So after doing some research and testing, I found it was quite tricky to make Code Actions bind to a keyboard shortcut.

The simplest way might be through [Commands](https://code.visualstudio.com/api/extension-guides/command), but it requires a duplicate implementation to register it within VSCode. And after reading the docs and looking through examples, I'm still unsure of the implementation details of how to do this, including whether document selections can be accessed through commands.

The other way is through [keybinding Code Actions](https://github.com/microsoft/vscode/issues/33049), but this doesn't actually do the thing you might be looking for. These keybindings don't allow for specific actions to be used, only general categories of actions. This means it still won't trigger the action even if you press the keyboard shortcut.

So for solving your problem of speed, it might be faster to just use the keybind for Refactor (CTRL+SHIFT+R) then use the up and down arrow keys to select the right action.

As for your other ideas:
* VSCode does some sort of string matching after running a Code Action to automatically select similar looking text. There doesn't seem to be an API feature to allow different selections after an action, but I'm sure some way of doing this exists. For now, I haven't been able to solve this issue.
* I've changed the name of the actions to Escape code (Markdown). I omitted Moodle since if you're using the GIFT language you're likely using it for Moodle anyway.
* I've already made this change for single line use. If your code block is on a single line and you run the refactor, it'll automatically find the first and second backticks blocks and unescape everything in it. It will however remove all backtick blocks on that line, including ones that occur after the first and second blocks. This was done to keep the implementation stateless, which makes it simpler to maintain. For selections, I didn't make assumptions since large masses of text outside of the selection might be escaped if no backticks are found.

**Comment by fuhrmanator** [comment]
I've never written an extension, but I found [this simple example that gets a selection and reverses it](https://github.com/microsoft/vscode-extension-samples/blob/main/document-editing-sample/src/extension.ts). It appears to be a command (at least in the Readme animation).

**Comment by ethan-ou** [comment]
Good thing you found the example. I had a couple of attempts searching through the repo for similar examples but couldn't find anything that matched, so I'm glad you picked up on this one.

The commands for the code actions should now be available with this build:

[vscode-gift-0.1.8.vsix.zip](https://github.com/ethan-ou/vscode-gift/files/6989466/vscode-gift-0.1.8.vsix.zip)

They should be named:
* Gift: Escape special characters
* Gift: Escape code block (Markdown)
* Gift: Unescape special characters
* Gift: Unescape code block (Markdown)

The text selection after applying these commands will be slightly different to the Code Actions versions, but this isn't due to any differences in implementation.

Give it a try and see if you're able to keybind to them.

**Comment by fuhrmanator** [comment]
It works well (so far). I used the VSCode GUI option to map the key to the command, but it creates this JSON:

```json
    {
        "key": "ctrl+shift+alt+w",
        "command": "gift.escapeMarkdownCodeBlock",
        "when": "editorLangId == 'gift' && editorHasSelection && editorTextFocus && !editorReadonly"
    }
```

I looked up the `when:` options and I think they're correct, but it probably doesn't matter much.

Thanks for making the change.
